### ISSUE TITLE
Failed to link `libgbm` on `nixos-unstable`

### ISSUE THREAD

**Issue by emenel** [sodiboo/niri-flake#921]
Hi. I ran a flake update this morning and am now running into a build failure for Niri unstable.

Here's the error part of the output:

```
niri> error: could not compile `niri` (bin "niri") due to 1 previous error
error: builder for '/nix/store/j8vb765jj8gbcwhr8m3ypznkdsrhfv20-niri-unstable-2025-03-16-287480b.drv' failed with exit code 101;
       last 25 log lines:
       >    Compiling clap_complete v4.5.46
       >    Compiling atomic v0.6.0
       >    Compiling zbus_macros v5.5.0
       >    Compiling ordered-float v5.0.0
       >    Compiling keyframe v1.1.1
       >    Compiling sd-notify v0.4.5
       >    Compiling glam v0.30.0
       >    Compiling arrayvec v0.7.6
       >    Compiling glib v0.20.9
       >    Compiling zbus v5.5.0
       >    Compiling pipewire v0.8.0 (https://gitlab.freedesktop.org/pipewire/pipewire-rs.git#fd3d8f78)
       >    Compiling cairo-rs v0.20.7
       >    Compiling pango v0.20.9
       >    Compiling niri-config v25.2.0 (/build/source/niri-config)
       >    Compiling pangocairo v0.20.7
       >    Compiling niri v25.2.0 (/build/source)
       > error: linking with `/nix/store/gj9lra51hwhxnhz05jqk5lh03wipamv0-gcc-wrapper-14-20241116/bin/cc` failed: exit status: 1
       >   |
       >   = note: LC_ALL="C" PATH="/nix/store/464j7y43imzxc94955xgysxxcnadaah0-rustc-1.85.0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/wvcl683adl5vsc2873rdcs255zq3j7yk-cargo-1.85.0/bin:/nix/store/q88m6mq2pbd8nq7dr0p065334nsglqhr-cargo-auditable-0.6.5/bin:/nix/store/8cczxvv6hpngc9mxal0wx0lzny4vjp4n-pkg-config-wrapper-0.29.2/bin:/nix/store/2b3ahc691h5syn9qp18fkps6hp1n0rdl-auditable-cargo-1.85.0/bin:/nix/store/fsyj2gv51gcwcs8gx44xix044hb716a5-rustc-wrapper-1.85.0/bin:/nix/store/wvcl683adl5vsc2873rdcs255zq3j7yk-cargo-1.85.0/bin:/nix/store/qp4a5bxdck7c0w7l2mf47phhfk2nmscs-patchelf-0.15.0/bin:/nix/store/gj9lra51hwhxnhz05jqk5lh03wipamv0-gcc-wrapper-14-20241116/bin:/nix/store/aw0qxjd1phf16qhlwpdb4x87yymfv9rp-gcc-14-20241116/bin:/nix/store/cgp5cbv6b3djw35zkl4s77snh0navr3w-glibc-2.40-66-bin/bin:/nix/store/vz67zaqyfln2jcqwar682kdlrxfx9vq1-coreutils-9.6/bin:/nix/store/kinjsav83qgiiy8mwgypnnc9sn8m8r9y-binutils-wrapper-2.43.1/bin:/nix/store/dh0m67pv8snfcx1ic18jzp0x4cb10zhc-binutils-2.43.1/bin:/nix/store/vz67zaqyfln2jcqwar682kdlrxfx9vq1-coreutils-9.6/bin:/nix/store/cfd3hysxk7b4m584s539hzm2bc013lsg-findutils-4.10.0/bin:/nix/store/kdrp6y7k352jb9ysjprzvmrlmiblz0jq-diffutils-3.10/bin:/nix/store/l97jblhqk9ga2dl01ysd3wf51mwqcd6s-gnused-4.9/bin:/nix/store/h3xhfhg0vv3k3hvkcwkmdg99r4zm9mcl-gnugrep-3.11/bin:/nix/store/kz9cfpxf08fdsgxgh6zp1k1y5npsnjpr-gawk-5.3.1/bin:/nix/store/j9gjzsbag34n3ic3yg4ra0p5yl8wcbhg-gnutar-1.35/bin:/nix/store/g9h265xkvsma74irj4389djs39k96d72-gzip-1.13/bin:/nix/store/p406mc3r448lfrl0qgqm4cg8qax7jw5v-bzip2-1.0.8-bin/bin:/nix/store/zkman1hvq58ica17s06r9hq62k300c1v-gnumake-4.4.1/bin:/nix/store/ki4if6b0w5bqv8dc5lrjp8xm7wjy9dlf-bash-5.2p37/bin:/nix/store/gkw3fwmfvn06gz7hh6vwdskh3s1lkvcv-patch-2.7.6/bin:/nix/store/7w6d3dwm5zs6vn37wmsbi0szvx0w98gy-xz-5.6.4-bin/bin:/nix/store/i4fn3frirjgrfsmwkbr4srfpry18x5dz-file-5.46/bin" VSLANG="1033" "/nix/store/gj9lra51hwhxnhz05jqk5lh03wipamv0-gcc-wrapper-14-20241116/bin/cc" "-m64" "/build/rustcAEFyU3/symbols.o" "<1218 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/build/rustcAEFyU3/{liblibspa-0fecb8f1d5cf8882.rlib,liblibspa_sys-4b09195f109e680c.rlib}" "/nix/store/464j7y43imzxc94955xgysxxcnadaah0-rustc-1.85.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libcompiler_builtins-b15b4ec8580e3dd7.rlib}" "-Wl,-Bdynamic" "-lpipewire-0.3" "-lpipewire-0.3" "-lpangocairo-1.0" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lharfbuzz" "-lcairo" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lharfbuzz" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lgobject-2.0" "-lglib-2.0" "-lcairo-gobject" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lgobject-2.0" "-lglib-2.0" "-ldisplay-info" "-lseat" "-ludev" "-linput" "-ldl" "-lpixman-1" "-lxkbcommon" "-ldl" "-lgbm" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/nix/store/48jgb2ihb9ccgqmwcdgwkg8vbrwcn169-systemd-minimal-libs-257.3/lib" "-L" "/nix/store/sy0n827w0ccnl4izd50qbijmnc9np852-libdisplay-info-0.2.0/lib" "-L" "/nix/store/22svsj3ivbibhksnd7lwawdnk7wgbz9a-seatd-0.9.1/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/3fnl15840l1pjj7k6yypwv3hxdsp5wam-pango-1.56.1/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/zr9wda9pmmzrkv8hisck3vplcpds7k7b-harfbuzz-10.2.0/lib" "-L" "/nix/store/0713644mps95ixcbbpip5kbvyzaad8r0-cairo-1.18.2/lib" "-L" "/nix/store/0713644mps95ixcbbpip5kbvyzaad8r0-cairo-1.18.2/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/3fnl15840l1pjj7k6yypwv3hxdsp5wam-pango-1.56.1/lib" "-L" "/nix/store/0713644mps95ixcbbpip5kbvyzaad8r0-cairo-1.18.2/lib" "-L" "/nix/store/7ly9p55j21sr0rl93lb6vpi1k1sbb3x3-glib-2.82.4/lib" "-L" "/nix/store/zr9wda9pmmzrkv8hisck3vplcpds7k7b-harfbuzz-10.2.0/lib" "-L" "/build/source/target/x86_64-unknown-linux-gnu/release/build/libspa-35687c094f18563d/out" "-L" "/nix/store/nvj68rjl3f4900dba9gxynabzqg5m85n-pipewire-1.4.0/lib" "-L" "/build/source/target/x86_64-unknown-linux-gnu/release/build/libspa-sys-4d09b3bb27d8e5d3/out" "-L" "/nix/store/nvj68rjl3f4900dba9gxynabzqg5m85n-pipewire-1.4.0/lib" "-L" "/nix/store/464j7y43imzxc94955xgysxxcnadaah0-rustc-1.85.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/build/source/target/x86_64-unknown-linux-gnu/release/deps/niri-792b42b06db39368" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-Wl,--push-state,--no-as-needed" "-lEGL" "-lwayland-client" "-Wl,--pop-state" "/build/source/target/x86_64-unknown-linux-gnu/release/deps/niri_audit_data.o" "-Wl,--undefined=AUDITABLE_VERSION_INFO"
       >   = note: some arguments are omitted. use `--verbose` to show all linker arguments
       >   = note: /nix/store/dh0m67pv8snfcx1ic18jzp0x4cb10zhc-binutils-2.43.1/bin/ld: cannot find -lgbm: No such file or directory
       >           collect2: error: ld returned 1 exit status
       >
       >
       > error: could not compile `niri` (bin "niri") due to 1 previous error
       For full logs, run 'nix log /nix/store/j8vb765jj8gbcwhr8m3ypznkdsrhfv20-niri-unstable-2025-03-16-287480b.drv'.
error: 1 dependencies of derivation '/nix/store/cm0lqa4a12dn6szywxfl4005hd3j38w5-config.kdl.drv' failed to build
error: 1 dependencies of derivation '/nix/store/583plsqqcqh20wrlk7pybbvycx1qfp6k-desktops.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i8d0l368n1rj8rbxqinvkwc0b3chy5y2-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g9a7x1yxiiacbgipgdrgz2prqwi28an9-niri-unstable-2025-03-16-287480b_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ndl6vakghaz1kyjsz7yrk9j7b443nhwn-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1j8v41v3b4lkhgjwg0y7y0r6j83x74ga-nixos-system-eddie-25.05.20250315.c80f6a7.drv' failed to build
```

**Comment by nivaddo** [comment]
Can report the same build failure.

**Comment by Chucklee1** [comment]
I too am also getting the same build failure. This is the full log for mine:
```
$ nix log /nix/store/j8vb765jj8gbcwhr8m3ypznkdsrhfv20-niri-unstable-2025-03-16-287480b.drv
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/8q8mvdfkh3dcx6ivf37jlkfm432iqsf1-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
patching script interpreter paths in resources/niri-session
resources/niri-session: interpreter directive changed from "#!/bin/sh" to "/nix/store/ki4if6b0w5bqv8dc5lrjp8xm7wjy9dlf-bash-5.2p37/bin/sh"
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing cargoBuildHook
cargoBuildHook flags: -j 12 --target x86_64-unknown-linux-gnu --offline --profile release --no-default-features --features=dbus\,xdp-gnome-screencast\,systemd
   Compiling proc-macro2 v1.0.94
   Compiling unicode-ident v1.0.18
   Compiling pkg-config v0.3.32
   Compiling libc v0.2.171
   Compiling serde v1.0.219
   Compiling winnow v0.7.4
   Compiling hashbrown v0.15.2
   Compiling equivalent v1.0.2
   Compiling autocfg v1.4.0
   Compiling heck v0.5.0
   Compiling cfg-if v1.0.0
   Compiling target-lexicon v0.12.16
   Compiling smallvec v1.14.0
   Compiling bitflags v2.9.0
   Compiling once_cell v1.21.1
   Compiling version-compare v0.2.0
   Compiling shlex v1.3.0
   Compiling pin-project-lite v0.2.16
   Compiling log v0.4.26
   Compiling rustix v0.38.44
   Compiling linux-raw-sys v0.4.15
   Compiling cc v1.2.16
   Compiling memchr v2.7.4
   Compiling slab v0.4.9
   Compiling indexmap v2.8.0
   Compiling memoffset v0.9.1
   Compiling futures-core v0.3.31
   Compiling futures-io v0.3.31
   Compiling cfg-expr v0.17.2
   Compiling quote v1.0.40
   Compiling libloading v0.8.6
   Compiling syn v2.0.100
   Compiling dlib v0.5.2
   Compiling wayland-sys v0.31.6
   Compiling version_check v0.9.5
   Compiling downcast-rs v1.2.1
   Compiling scoped-tls v1.0.1
   Compiling tracing-core v0.1.33
   Compiling crossbeam-utils v0.8.21
   Compiling quick-xml v0.37.2
   Compiling glob v0.3.2
   Compiling parking v2.2.1
   Compiling thiserror v1.0.69
   Compiling clang-sys v1.8.1
   Compiling regex-syntax v0.8.5
   Compiling minimal-lexical v0.2.1
   Compiling concurrent-queue v2.5.0
   Compiling wayland-client v0.31.8
   Compiling fastrand v2.3.0
   Compiling futures-sink v0.3.31
   Compiling stable_deref_trait v1.2.0
   Compiling futures-channel v0.3.31
   Compiling nom v7.1.3
   Compiling wayland-scanner v0.31.6
   Compiling cfg-expr v0.15.8
   Compiling wayland-backend v0.3.8
   Compiling bindgen v0.69.5
   Compiling yansi-term v0.1.2
   Compiling futures-task v0.3.31
   Compiling cfg_aliases v0.2.1
   Compiling either v1.15.0
   Compiling unicode-width v0.1.14
   Compiling pin-utils v0.1.0
   Compiling getrandom v0.2.15
   Compiling event-listener v5.4.0
   Compiling itertools v0.12.1
   Compiling annotate-snippets v0.9.2
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling lazy_static v1.5.0
   Compiling event-listener-strategy v0.5.3
   Compiling libm v0.2.11
   Compiling ahash v0.8.11
   Compiling num-traits v0.2.19
   Compiling drm-fourcc v2.2.0
   Compiling regex-automata v0.4.9
   Compiling async-task v4.7.1
   Compiling writeable v0.5.5
   Compiling litemap v0.7.4
   Compiling drm-sys v0.8.0
   Compiling static_assertions v1.1.0
   Compiling futures-lite v2.6.0
   Compiling utf8parse v0.2.2
   Compiling khronos_api v3.1.0
   Compiling semver v1.0.26
   Compiling cexpr v0.6.0
   Compiling linux-raw-sys v0.6.5
   Compiling zerocopy v0.8.23
   Compiling zerocopy v0.7.35
   Compiling anstyle-parse v0.2.6
   Compiling is-terminal v0.4.16
   Compiling proc-macro-error-attr v1.0.4
   Compiling libudev-sys v0.1.4
   Compiling rand_core v0.6.4
   Compiling regex v1.11.1
   Compiling xkeysym v0.2.1
   Compiling colorchoice v1.0.3
   Compiling io-lifetimes v1.0.11
   Compiling siphasher v1.0.1
   Compiling anstyle v1.0.10
   Compiling icu_locid_transform_data v1.5.0
   Compiling anstyle-query v1.1.2
   Compiling syn v1.0.109
   Compiling is_terminal_polyfill v1.70.1
   Compiling phf_shared v0.11.3
   Compiling anstream v0.6.18
   Compiling synstructure v0.13.1
   Compiling rand v0.8.5
   Compiling async-lock v3.4.0
   Compiling nix v0.29.0
   Compiling memmap2 v0.9.5
   Compiling proc-macro-error v1.0.4
   Compiling libseat-sys v0.1.9
   Compiling x11-dl v2.21.0
   Compiling pixman-sys v0.1.0
   Compiling rustix v1.0.2
   Compiling percent-encoding v2.3.1
   Compiling getrandom v0.3.1
   Compiling smithay-client-toolkit v0.19.2
   Compiling icu_properties_data v1.5.0
   Compiling gbm-sys v0.4.0
   Compiling strsim v0.11.1
   Compiling paste v1.0.15
   Compiling clap_lex v0.7.4
   Compiling xml-rs v0.8.25
   Compiling xcursor v0.3.8
   Compiling input-sys v1.18.0
   Compiling cursor-icon v1.1.0
   Compiling clap_builder v4.5.32
   Compiling phf_generator v0.11.3
   Compiling gl_generator v0.14.0
   Compiling ppv-lite86 v0.2.21
   Compiling async-channel v2.3.1
   Compiling drm-ffi v0.9.0
   Compiling winit v0.30.9
   Compiling tracy-client-sys v0.24.3
   Compiling aho-corasick v1.1.3
   Compiling cgmath v0.18.0
   Compiling unicode-linebreak v0.1.5
   Compiling unicode-segmentation v1.12.0
   Compiling serde_derive v1.0.219
   Compiling tracing-attributes v0.1.28
   Compiling zerofrom-derive v0.1.6
   Compiling yoke-derive v0.7.5
   Compiling thiserror-impl v1.0.69
   Compiling zerovec-derive v0.10.3
   Compiling futures-macro v0.3.31
   Compiling tracing v0.1.41
   Compiling polling v3.7.4
   Compiling zerofrom v0.1.5
   Compiling yoke v0.7.5
   Compiling displaydoc v0.2.5
   Compiling wayland-server v0.31.7
   Compiling enumflags2_derive v0.7.11
   Compiling zerovec v0.10.4
   Compiling futures-util v0.3.31
   Compiling bytemuck_derive v1.8.1
   Compiling icu_provider_macros v1.5.0
   Compiling wayland-protocols v0.32.6
   Compiling tinystr v0.7.6
   Compiling icu_locid v1.5.0
   Compiling icu_collections v1.5.0
   Compiling bytemuck v1.22.0
   Compiling icu_provider v1.5.0
   Compiling calloop v0.13.0
   Compiling icu_locid_transform v1.5.0
   Compiling calloop-wayland-source v0.3.0
   Compiling drm v0.14.1
   Compiling wayland-cursor v0.31.8
   Compiling wayland-csd-frame v0.3.0
   Compiling clap_derive v4.5.32
   Compiling write16 v1.0.0
   Compiling smawk v0.3.2
   Compiling icu_properties v1.5.1
   Compiling serde_json v1.0.140
   Compiling x11rb-protocol v0.13.1
   Compiling futures-executor v0.3.31
   Compiling as-raw-xcb-connection v1.0.1
   Compiling linux-raw-sys v0.9.3
   Compiling allocator-api2 v0.2.21
   Compiling serde_spanned v0.6.8
   Compiling toml_datetime v0.6.8
   Compiling zvariant_utils v3.2.0
   Compiling enumflags2 v0.7.11
   Compiling thiserror v2.0.12
   Compiling is_ci v1.2.0
   Compiling toml_edit v0.22.24
   Compiling icu_normalizer_data v1.5.0
   Compiling simd-adler32 v0.3.7
   Compiling gio v0.20.9
   Compiling endi v1.1.0
   Compiling atomic-waker v1.1.2
   Compiling libseat v0.2.3
   Compiling utf16_iter v1.0.5
   Compiling utf8_iter v1.0.4
   Compiling piper v0.2.4
   Compiling supports-color v2.1.0
   Compiling textwrap v0.15.2
   Compiling hashbrown v0.14.5
   Compiling icu_normalizer v1.5.0
   Compiling clap v4.5.32
   Compiling futures v0.3.31
   Compiling async-io v2.4.0
   Compiling heck v0.4.1
   Compiling toml v0.8.20
   Compiling proc-macro-crate v3.3.0
   Compiling system-deps v7.0.3
   Compiling system-deps v6.2.2
   Compiling phf_macros v0.11.3
   Compiling miette-derive v5.10.0
   Compiling thiserror-impl v2.0.12
   Compiling profiling-procmacros v1.0.16
   Compiling smithay v0.5.0 (https://github.com/Smithay/smithay.git#cfbf4740)
   Compiling rand_chacha v0.3.1
   Compiling udev v0.9.3
   Compiling glib-sys v0.20.9
   Compiling gobject-sys v0.20.9
   Compiling gio-sys v0.20.9
   Compiling libspa-sys v0.8.0 (https://gitlab.freedesktop.org/pipewire/pipewire-rs.git#fd3d8f78)
   Compiling zvariant_derive v5.4.0
   Compiling glib-macros v0.20.7
   Compiling cairo-sys-rs v0.20.7
   Compiling pango-sys v0.20.9
   Compiling libdisplay-info-sys v0.2.2
   Compiling pipewire-sys v0.8.0 (https://gitlab.freedesktop.org/pipewire/pipewire-rs.git#fd3d8f78)
   Compiling pangocairo-sys v0.20.7
   Compiling libspa v0.8.0 (https://gitlab.freedesktop.org/pipewire/pipewire-rs.git#fd3d8f78)
   Compiling zvariant v5.4.0
   Compiling xkbcommon-dl v0.4.2
   Compiling approx v0.4.0
   Compiling supports-unicode v2.1.0
   Compiling supports-hyperlinks v2.1.0
   Compiling signal-hook-registry v1.4.2
   Compiling errno v0.3.10
   Compiling wayland-protocols-wlr v0.3.6
   Compiling wayland-protocols-plasma v0.3.6
   Compiling terminal_size v0.1.17
   Compiling itoa v1.0.15
   Compiling anyhow v1.0.97
   Compiling owo-colors v3.5.0
   Compiling dpi v0.1.1
   Compiling regex-syntax v0.6.29
   Compiling adler2 v2.0.0
   Compiling raw-window-handle v0.6.2
   Compiling smol_str v0.2.2
   Compiling ryu v1.0.20
   Compiling glib v0.20.9
   Compiling regex-automata v0.1.10
   Compiling convert_case v0.6.0
   Compiling miniz_oxide v0.8.5
   Compiling x11rb v0.13.1
   Compiling miette v5.10.0
   Compiling zbus_names v4.2.0
   Compiling async-signal v0.2.10
   Compiling wayland-protocols-misc v0.3.6
   Compiling pixman v0.2.1
   Compiling gbm v0.18.0
   Compiling tempfile v3.19.0
   Compiling input v0.9.1
   Compiling profiling v1.0.16
   Compiling phf v0.11.3
   Compiling knuffel-derive v3.2.0
   Compiling cookie-factory v0.3.3
   Compiling chumsky v0.9.3
   Compiling idna_adapter v1.2.0
   Compiling blocking v1.6.1
   Compiling calloop v0.14.2
   Compiling wayland-egl v0.32.5
   Compiling libdisplay-info-derive v0.1.0
   Compiling xkbcommon v0.8.0
   Compiling crc32fast v1.4.2
   Compiling option-ext v0.2.0
   Compiling base64 v0.21.7
   Compiling overload v0.1.1
   Compiling appendlist v1.4.0
   Compiling aliasable v0.1.3
   Compiling portable-atomic v1.11.0
   Compiling sharded-slab v0.1.7
   Compiling nu-ansi-term v0.46.0
   Compiling dirs-sys v0.5.0
   Compiling libdisplay-info v0.2.2
   Compiling flate2 v1.1.0
   Compiling async-fs v2.1.2
   Compiling idna v1.0.3
   Compiling tracy-client v0.18.0
   Compiling csscolorparser v0.7.0
   Compiling zbus_macros v5.5.0
   Compiling knuffel v3.2.0
   Compiling async-process v2.3.0
   Compiling niri-ipc v25.2.0 (/build/source/niri-ipc)
   Compiling cairo-rs v0.20.7
   Compiling matchers v0.1.0
   Compiling fdeflate v0.3.7
   Compiling serde_repr v0.1.20
   Compiling async-trait v0.1.88
   Compiling git-version-macro v0.3.9
   Compiling form_urlencoded v1.2.1
   Compiling async-executor v1.13.1
   Compiling async-broadcast v0.7.2
   Compiling xdg-home v1.3.0
   Compiling tracing-log v0.2.0
   Compiling ordered-stream v0.2.0
   Compiling thread_local v1.1.8
   Compiling bitflags v1.3.2
   Compiling hex v0.4.3
   Compiling png v0.17.16
   Compiling tracing-subscriber v0.3.19
   Compiling git-version v0.3.9
   Compiling url v2.5.4
   Compiling pipewire v0.8.0 (https://gitlab.freedesktop.org/pipewire/pipewire-rs.git#fd3d8f78)
   Compiling smithay-drm-extras v0.1.0 (https://github.com/Smithay/smithay.git#cfbf4740)
   Compiling zbus v5.5.0
   Compiling directories v6.0.0
   Compiling clap_complete v4.5.46
   Compiling atomic v0.6.0
   Compiling keyframe v1.1.1
   Compiling ordered-float v5.0.0
   Compiling sd-notify v0.4.5
   Compiling arrayvec v0.7.6
   Compiling glam v0.30.0
   Compiling pango v0.20.9
   Compiling pangocairo v0.20.7
   Compiling niri-config v25.2.0 (/build/source/niri-config)
   Compiling niri v25.2.0 (/build/source)
error: linking with `/nix/store/gj9lra51hwhxnhz05jqk5lh03wipamv0-gcc-wrapper-14-20241116/bin/cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/nix/store/464j7y43imzxc94955xgysxxcnadaah0-rustc-1.85.0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/wvcl683adl5vsc2873rdcs255zq3j7yk-cargo-1.85.0/bin:/>
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: /nix/store/dh0m67pv8snfcx1ic18jzp0x4cb10zhc-binutils-2.43.1/bin/ld: cannot find -lgbm: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `niri` (bin "niri") due to 1 previous error
```

**Comment by Chucklee1** [comment]
Just ran a check again. It might have something to do with pipewire-rs. I saw the pipewire-rs links next to the compile steps on [emenel](https://github.com/emenel) comment too. Does anyone think that has something to do with the error?

**Comment by emenel** [comment]
oh... i just checked the freedesktop.org gitlab and saw this:

`Currently planned outage: 2025-03-16 -> 2025-03-22`

... maybe that is breaking things?

**Comment by Chucklee1** [comment]
It most likely is. The best action would probably to move back to a stable release of niri or see if someone can move the current version of pipewire niri is using. Pretty sure this is also only affecting the flake version of niri since I am not seeing any issues with YaLTeRs niri

**Comment by emenel** [comment]
> It most likely is. The best action would probably to move back to a stable release of niri or see if someone can move the current version of pipewire niri is using. Pretty sure this is also only affecting the flake version of niri since I am not seeing any issues with YaLTeRs niri

yeah, it seems like a nix specific issue.

**Comment by asonix** [comment]
adding `libgbm` as a build dependency should fix the original reported issue, which is unrelated to pipewire-rs' repo being down.

**Comment by emenel** [comment]
When i don't update nixpkgs, but only update the niri flake, i can rebuild successfully.... that points to a problem related to a nixpkgs update...

**Comment by Chucklee1** [comment]
Adding libgbm did not fix my issue. What did fix it was specifying the rev hashes for nixpkgs back to around 02/15.

**Comment by feathecutie** [comment]
I got the same build failure on latest nixpkgs (`nixos-unstable`) and latest niri-unstable, but for me it worked to simply add

```nix
package = pkgs.niri-unstable.overrideAttrs (prev:
  buildInputs = prev.buildInputs ++ [ pkgs.libgbm ];
});
```

With this override, I'm able to build niri without problems again.

I suspect this issue might be caused by https://github.com/NixOS/nixpkgs/pull/387292 since this seems to be most recent thing messing with mesa and libgbm, but I'm not entirely sure what that PR actually *does* so that's mostly a guess.

**Comment by Vortriz** [comment]
> Same thing for me. Adding libgbm did not fix my issue. What did fix it was specifying the rev hashes for nixpkgs back to around 02/15.

then it is due the freedesktop gitlab being down. cant pull deps because of that.

pin the niri flake to a previous version for a week, till the issue is solved.

**Comment by sodiboo** [comment]
Hey y'all. There are two issues reported here. I've gone ahead and pushed a commit fixing the one with mesa. Builds work again now on unstable NixOS. That is, **assuming you have pipewire-rs cached locally**. The freedesktop gitlab is currently down, so you won't be able to build it (even with fixed mesa) if you haven't done so previously.

- #923
